BBPATH .= ":${LAYERDIR}"
BBFILES += "\
            ${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend \
           "

BBFILE_COLLECTIONS += "sbc"
BBFILE_PATTERN_sbc := "^${LAYERDIR}/"
BBFILE_PRIORITY_sbc = "20"

LAYERDEPENDS_sbc = "core"
LAYERSERIES_COMPAT_sbc = "wrynose"
